// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ_sCzGGyE2D4PhYG7GtMgDWab4byWbEs',
    appId: '1:789582469873:web:635f65858ad2f9a2342750',
    messagingSenderId: '789582469873',
    projectId: 'booking-dimah',
    authDomain: 'booking-dimah.firebaseapp.com',
    storageBucket: 'booking-dimah.firebasestorage.app',
    measurementId: 'G-8BF0SWJ8CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIP2K02cL849AeimdkKS_X3BsKEuhLsxA',
    appId: '1:789582469873:android:b7ba3283b1eda5f4342750',
    messagingSenderId: '789582469873',
    projectId: 'booking-dimah',
    storageBucket: 'booking-dimah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54YBx63BUsAhYEUIBIRbC1d5wgQWnEm4',
    appId: '1:789582469873:ios:c99c3236bbbe7ee6342750',
    messagingSenderId: '789582469873',
    projectId: 'booking-dimah',
    storageBucket: 'booking-dimah.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54YBx63BUsAhYEUIBIRbC1d5wgQWnEm4',
    appId: '1:789582469873:ios:c99c3236bbbe7ee6342750',
    messagingSenderId: '789582469873',
    projectId: 'booking-dimah',
    storageBucket: 'booking-dimah.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ_sCzGGyE2D4PhYG7GtMgDWab4byWbEs',
    appId: '1:789582469873:web:5aaf35f32d2b96bb342750',
    messagingSenderId: '789582469873',
    projectId: 'booking-dimah',
    authDomain: 'booking-dimah.firebaseapp.com',
    storageBucket: 'booking-dimah.firebasestorage.app',
    measurementId: 'G-4J0BTPMY6Q',
  );
}
